---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
- deployment.yml
- service.yml
- ingress.yml

vars:
 - name: DOMAIN_NAME
   literals:
     - $(DOMAIN_NAME)

commonLabels:
  app.kubernetes.io/name: server

commonAnnotations:
  app.kubernetes.io/name: server
  app.kubernetes.io/managed-by: kustomization
  app.kubernetes.io/tier: frontend