sudo: required
services:
  - docker
install: true
env:
  - DOCKER_BUILDKIT=1
  - BUILDX_VERSION=v0.3.1
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - wget https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64
  - chmod +x buildx-$BUILDX_VERSION.linux-amd64
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
