sudo: required
services:
  - docker
install: true
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
