dist: xenial
sudo: required
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
after_success:
  - echo "All done!"
