FROM saidsef/armhf:alpine-python
MAINTAINER Said Sef <saidsef@gmail.com> (saidsef.co.uk/)

ARG BUILD_ID=""
ARG PORT=""

ENV BUILD_ID ${BUILD_ID:-'0.0.0.0-boo!'}
ENV PORT ${PORT:-80}

WORKDIR /code
COPY ./app/ /code

RUN apk add -U --no-cache nodejs npm bash
RUN echo ${BUILD_ID} > build_id.txt
RUN npm install && \
    npm shrinkwrap

EXPOSE ${PORT}

CMD ["run", "start"]
ENTRYPOINT ["npm"]
