FROM saidsef/armhf:alpine-python
MAINTAINER Said Sef <saidsef@gmail.com> (saidsef.co.uk/)

ARG BUILD_ID=""
ARG PORT=""

ENV NODE_ENV production
ENV NPM_CONFIG_FETCH_RETRIES 10
ENV NPM_CONFIG_LOGLEVEL warn
ENV BUILD_ID ${BUILD_ID:-'0.0.0.0-boo!'}
ENV PORT ${PORT:-8080}

WORKDIR /code
COPY ./app/ /code

RUN apk add -U --no-cache nodejs npm
RUN echo ${BUILD_ID} > build_id.txt
RUN npm install && \
    npm shrinkwrap

EXPOSE ${PORT}

CMD ["run", "start"]
ENTRYPOINT ["npm"]
