apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: server-pr-testing
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: saidsef
        repo: node-webserver
        labels:
        - preview
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 120
  template:
    metadata:
      name: 'server-{{branch}}-{{number}}'
      annotations:
        argocd.argoproj.io/head: '{{head_sha}}'
    spec:
      source:
        repoURL: 'https://github.com/saidsef/node-webserver.git'
        targetRevision: '{{head_sha}}'
        kustomize:
          # patches:
          # - target:
          #     kind: Ingress
          #     version: v1
          #     name: server
          #   patch: |-
          #     - op: replace
          #       path: /spec/rules/o/host
          #       value: server-preview.saidsef.co.uk
          images:
          - 'docker.io/saidsef/node-webserver:{{branch}}'
        path: deployment
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'server-{{branch}}-{{number}}'
