kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: server
spec:
  parentRefs:
  - kind: Gateway
    name: external-gw
    namespace: gateway-ingress
    sectionName: https
  rules:
  - matches:
    - path:
        value: /hello
    backendRefs:
    - name: server
      port: 8080
