apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base


commonAnnotations:
  app.kubernetes.io/managed-by: kustomization
  app.kubernetes.io/name: server
  app.kubernetes.io/tier: frontend

images:
- name: server
  newName: docker.io/saidsef/node-webserver
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: server
