---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/tier: frontend
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
