apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: server-pr-testing
  namespace: argocd
spec:
  generators:
  - clusters: {}
  - pullRequest:
      github:
        owner: saidsef
        repo: node-webserver
        labels:
        - preview
      requeueAfterSeconds: 120
  template:
    metadata:
      name: 'server-{{branch}}-{{number}}'
      annotations:
        argocd.argoproj.io/head: '{{head_sha}}'
    spec:
      source:
        repoURL: 'https://github.com/saidsef/node-webserver.git'
        targetRevision: '{{head_sha}}'
        path: deployment
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: '{{server}}''
        namespace: 'server-{{branch}}-{{number}}'
